# Generated by Django 5.2.12 on 2026-03-06 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='created_at',
        ),
    ]
